2.2b1

diff --git a/tests/test1.in b/tests/test1.in
--- a/tests/test1.in
+++ b/tests/test1.in
@@ -15,7 +15,7 @@ echo x-{1}
 echo x-{1,2}
 echo foo-{1,2{3,4}}
 
-# Escpaed newlines
+# Escaped newlines
 echo foo\ bar
 echo foo\
 bar
@@ -83,6 +83,11 @@ else
 end
 echo Test 4 $sta
 
+# Ensure eval doesn't unnecessarily mess with the exit status
+function empty_func ; end
+false ; eval empty_func ; echo $status
+true ; eval empty_func ; echo $status
+
 function test_builtin_status
 	return 1
 end
@@ -99,6 +104,12 @@ echo Test 5 $sta
 echo Test redirections
 begin ; echo output ; echo errput 1>&2  ; end 2>&1 | tee /tmp/tee_test.txt ; cat /tmp/tee_test.txt
 
+# Verify that we can pipe something other than stdout
+# The first line should be printed, since we output to stdout but pipe stderr to /dev/null
+# The second line should not be printed, since we output to stderr and pipe it to /dev/null
+begin ; echo is_stdout ; end 2>| cat > /dev/null
+begin ; echo is_stderr 1>&2 ; end 2>| cat > /dev/null
+
 # echo tests
 
 echo 'abc\ndef'
@@ -110,8 +121,50 @@ echo -e 'abc\121def'
 echo -e 'abc\1212def'
 echo -e 'abc\cdef' # won't output a newline!
 echo ''
+echo -
+
+echo -ne '\376' | xxd -p
 
 echo -e Catch your breath
 
 echo -e 'abc\x21def'
 echo -e 'abc\x211def'
+
+# Verify that pipes don’t conflict with fd redirections
+# This code is very similar to eval. We go over a bunch of fads
+# to make it likely that we will nominally conflict with a pipe
+# fish is supposed to detect this case and dup the pipe to something else
+echo "/bin/echo pipe 3 <&3 3<&-" | source 3<&0
+echo "/bin/echo pipe 4 <&4 4<&-" | source 4<&0
+echo "/bin/echo pipe 5 <&5 5<&-" | source 5<&0
+echo "/bin/echo pipe 6 <&6 6<&-" | source 6<&0
+echo "/bin/echo pipe 7 <&7 7<&-" | source 7<&0
+echo "/bin/echo pipe 8 <&8 8<&-" | source 8<&0
+echo "/bin/echo pipe 9 <&9 9<&-" | source 9<&0
+echo "/bin/echo pipe 10 <&10 10<&-" | source 10<&0
+echo "/bin/echo pipe 11 <&11 11<&-" | source 11<&0
+echo "/bin/echo pipe 12 <&12 12<&-" | source 12<&0
+
+
+# Make sure while loops don't run forever with no-exec (#1543)
+echo "Checking for infinite loops in no-execute"
+echo "while true; end" | ../fish --no-execute
+
+# Comments allowed in between lines (#1987)
+echo before comment \
+  # comment
+  after comment
+
+# Backslashes are part of comments and do not join lines (#1255)
+# This should execute false, not echo it
+echo -n # comment\
+false
+
+function always_fails
+    if true
+        return 1
+    end
+end
+
+always_fails ; echo $status
+
diff --git a/tests/test9.in b/tests/test9.in
--- a/tests/test9.in
+++ b/tests/test9.in
@@ -1,3 +1,4 @@
+# vim: set filetype=fish:
 # ensure that builtins that produce no output can still truncate files
 # (bug PCA almost reintroduced!)
 echo "Testing that builtins can truncate files"
@@ -35,3 +36,93 @@ emit test3 foo bar
 
 # test empty argument
 emit
+
+echo "Test break and continue"
+# This should output Ping once
+for i in a b c
+    if not contains $i c ; continue ; end
+    echo Ping
+end
+
+# This should output Pong not at all
+for i in a b c
+    if not contains $i c ; break ; end
+    echo Pong
+end
+
+# This should output Foop three times, and Boop not at all
+set i a a a
+while contains $i a
+    set -e i[-1]
+    echo Foop
+    continue
+    echo Boop
+end
+
+# This should output Doop once
+set i a a a
+while contains $i a
+    set -e i[-1]
+    echo Doop
+    break
+    echo Darp
+end
+
+# Test implicit cd. This should do nothing.
+./
+
+# Test special for loop expansion
+# Here we the name of the variable is derived from another variable
+echo "Testing for loop"
+set var1 var2
+for $var1 in 1 2 3
+    echo -n $var2
+end
+echo
+
+# Test status -n
+eval 'status -n
+status -n
+status -n'
+
+# Test psub
+cat (echo foo | psub)
+cat (echo bar | psub)
+cat (echo baz | psub)
+
+set -l filename (echo foo | psub)
+if test -e $filename
+    echo 'psub file was not deleted'
+else
+    echo 'psub file was deleted'
+end
+
+# Test support for unbalanced blocks
+function try_unbalanced_block
+    ../fish -c "echo $argv | source " 2>&1 | grep "Missing end" 1>&2
+end
+try_unbalanced_block 'begin'
+try_unbalanced_block 'while true'
+try_unbalanced_block 'for x in 1 2 3'
+try_unbalanced_block 'switch abc'
+try_unbalanced_block 'function anything'
+try_unbalanced_block 'if false'
+
+# Ensure that quoted keywords work
+'while' false; end
+"while" false; end
+"wh"'ile' false; "e"nd
+
+# BOM checking (see #1518)
+# But only in UTF8
+if locale | sgrep -q -i utf-8
+    echo \uFEFF"echo bom_test" | source
+else
+    echo "echo bom_test" | source
+end
+
+# Comments abutting text (#953)
+echo not#a#comment
+echo is # a # comment
+
+false
